// User-related types

/**
 * A user row, exactly as the database has it. Generated by Prisma from
 * prisma/schema.prisma rather than written by hand: the hand-written copy had
 * drifted (it listed a last_login_at column that does not exist and lacked
 * the avatar fields).
 */
export type { User } from '@prisma/client';

// Public user profile (no sensitive data)
export interface UserProfile {
  id: number;
  username: string;
  elo_rating: number;
  games_played: number;
  games_won: number;
  games_lost: number;
  highest_chain: number;
  total_garbage_sent: number;
  created_at: Date;
  rank?: number;
  level?: number;
  current_xp?: number;
  win_rate?: number;
  avatar_url?: string;
  is_admin?: boolean;
}

// Registration input
export interface CreateUserInput {
  username: string;
  password: string;
  email?: string;
}

// Login input
export interface LoginInput {
  username: string;
  password: string;
}

// Auth response
export interface AuthResponse {
  user: UserProfile;
  token: string;
}

// Leaderboard entry
export interface LeaderboardEntry {
  rank: number;
  id: number;
  username: string;
  elo_rating: number;
  games_played: number;
  games_won: number;
  win_rate: number;
}
